
* ссылки на схемы
event storming
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_event_storming.svg

data model
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_data_model_communications.svg

core domain chart
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_homework_core_domain_chart_make_cats_free.svg

bounded contexts
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_homework_bounded_context_and_subdomains.svg

architecture styels roundup
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_homework_styles_roundup.png

system structure
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_homework_system_chart.svg

* план
основная цель бизнеса
уменьшение посторонней работы котов-тестировщиков

выпишите все поддомены, которые вы нашли в системе;
** отделы
- биржа
- отдел по работе с воркерами
- отдел производства услуг
- склад
- отдел качества
- отдел расчетов с клиентами
- отдел расчетов с воркерами
- отдел вовлечения менеджеров

биржа решает несколько проблем
- продажа услуг
- матчинг
-  установка цены на услугу
- расчеты с клиентами

отдел по работе с воркерами решает несколько проблем
- привлечение и отсев воркеров
- исслеодование лучших способов отсева
- мотивация воркеров
- улучшение бизнеса

** поддомены
- биржа
- отдел по работе с воркерами
- исслеодование лучших способов отсева (не автоматизируем, только данные накапливаем и храним)
- тыгдыкание
- выдача расходников
- улучшение бизнеса  (не автоматизируем, только данные накапливаем и храним)
- увеличение мотивации менеджеров

| поддомен                            | конкурентное преимущество | сложность | изменчивость | интерес | вид поддомена |
|-------------------------------------+---------------------------+-----------+--------------+---------+---------------|
| биржа                               | да                        | высокая   | частая       | высокий | core          |
| отдел по работе с воркерами         | да                        | высокая   | частая       | высокий | core          |
| исследование лучших способов отсева | да                        | ???       | ???          | ???     | core          |
| тыгдыкание                          | нет                       | низкая    | редкая       | низкий  | supporting    |
| выдача расходников                  | нет                       | низкая    | редкая       | низкий  | generic       |
| увеличение мотивации менеджеров     | нет                       | низкая    | редкая       | низкая  | generic       |

определите все типы поддоменов и заполните core domain chart;
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_homework_core_domain_chart_make_cats_free.svg


** боундед контексты
определите боундед-контексты для каждого из поддоменов, основываясь на
требованиях (хватит одной модели, как было в уроке);

| поддомен                            | вид поддомена | выделенный bounded context                                                                             |
|-------------------------------------+---------------+--------------------------------------------------------------------------------------------------------|
| биржа                               | core          | продажа услуг, матчинг, определение стоимости услуги, расчеты с клиентами                              |
| привлечение и отсев воркеров        | core          | регистрация, планирование тестирования и тестирование воркеров, расчеты с воркерами, проверка качества |
| исследование лучших способов отсева | core          | не автоматизируем, копим данные                                                                        |
| тыгдыкание                          | supporting    | мобильное приложение для воркеров                                                                      |
| выдача расходников                  | generic       | подписка на 1с котосклад cloud                                                                         |
| увеличение мотивации менеджеров     | generic       | подписка на 1c gambling cloud                                                                          |

сравните полученные боундед-контексты из поддоменов и
боундед-контексты, полученные из ES. Опишите, что разошлось (можно
показать на картинке в сравнении) и предположения, почему так
получилось;

https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_homework_bounded_context_and_subdomains.svg

боундед контексты почти не изменились
связи между боундед контекстами стали более упорядоченными

сделайте исправленную версию ES-модели и модели данных, если
боундед-контексты разошлись. Если не разошлись — приложите ES и модель
данных из прошлого урока;

    если нашли места, где бизнес-команда разбилась на технические
    шаги, — отметьте эти места на модели;

** характеристики
выпишите характеристики, важные для проекта. В нашем случае мы не
можем спросить у бизнеса, что важно, а что нет;

    для каждой найденной характеристики укажите место, где она была
    взята;

agility, testability и deployability
Каждая из гипотез должна быть модульной и изолированной, а решение — дешёвым
Общие пожелания по системе

бюджет не ограничен
Контекст и проблема

Scalability
US-081

security
есть несколько ролей, US-050

modifiability, extensibility
US-060, US-070

модульность изолированность
этап жизни - проверка гипотезы

scalability
планирует расширяться в будущем

** архитектурные стили
выберите один из четырёх архитектурных стилей, описанных в уроке.
Опишите, почему вы сделали такой выбор и по каким характеристикам
сравнивали стили (можно использовать картинку из урока со сравнением
стилей);

Подходящий архитектурный стиль service-based
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_homework_styles_roundup.png

** модель системы
сделайте итоговую модель системы, укажите виды коммуникаций между
элементами, если выбрали распределённый стиль.

все коммуникации должны быть асинхронными кроме заказа печенек

https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/2_week_homework/2_week_homework_system_chart.svg
