* диаграммы
домашка нулевой недели и 4 недели
https://raw.githubusercontent.com/nmukhachev/system_architecture_homework/main/4_week_homework/4_week_homework_system_conversion.svg

* задание 1

Достать спроектированную систему из нулевой недели и сравнить её с
текущим результатом. Найти места, которые вы сделали иначе, чем
изначально планировали, что в текущем решении отличается от
изначального и что лично вам понравилось из решений.

Разница между домашкой 0 и финальной домашкой

- в 0 домашке я добавил отдельно сервисы уведомлений для каждого
  баундед контекста, где были необходимы уведомления.
  На курсе я узнал, что уведомления - это обычный вид вывода
  информации для пользователя, и что сервисы уведомлений в контексте
  бизнесовых задач обычно являются частью баундед контекстов.

- в 0 домашке я не воспользовался возможностью часть элементов системы
  приобрести в виде SaaS.
  Теперь стало понятно, по каким критериям можно принять решение о
  том, какие элементы системы стоит покупать на рынке, а какие — нужно
  реализовывать собственными ресурсами бизнеса. Это очень полезный навык.

- в 0 домашке я попытался сделать event-driven систему, как Антон
  показывал в курсе АА. И добавил в нее некоторое количество ошибок.
  Я не знал, как именно характеристики должны влиять на архитектуру
  системы. Обычно в курсах рассказывают, что характеристики очень
  важны, потом рассказывают про стили, но я ни разу до этого не видел
  сравнительных таблиц со звездами или другими спектрами. Этому довольно
  редко учат, и клево, что это оказалось в курсе. Очень круто, что
  Антон подчеркнул, что чаще всего достаточно набора из 12
  характеристик, а не вот те 80-100 штук, которые можно найти в
  википедии.

- в 0 домашке добавил несколько модулей, которые оказались
  несамостоятельными:
  - контроль качества
  - расчет скидок
  Тогда казалось, что систему на модули можно поделить на основании
  того, какие существительные есть в требованиях. Оказалось, что нужно
  внимательнее узнавать, какие у бизнеса на самом деле цели, и какие
  проблемы приходится решать, для того, чтобы этих целей достигнуть.

* задание 2

Выписать идеи и подходы, которые вы хотели бы внедрить в ваших рабочих
или других проектах, чтобы мы могли их обсудить и подумать, как лучше
всего внедрить каждую из идей или подходов.

** идея 1
Я часто вижу на разных предприятиях, что в моменты всяких транформаций и изменений ради изменений в продукты добавляют новых стейкхолдеров с довольно высоким влиянием и низкой заинтересованностью в результатах проекта.

Сейчас я со стороны продукта пытаюсь договориться с одним из таких стейкхолдеров о том, что часть их требований не должна быть применима к части продуктов, в том числе и тому, в котором я работаю. Пока что я выяснил, что эти стейкхолдеры уже год предъявляют требования к процессам всех продуктов, но не знают, какие у них есть цели, границы их действий и ограничения.

Я пока что им посоветовал всем в полном составе пойти на курсы https://hardsoftskills.by/system_engineering, чтобы у них хотя бы не возникало вопросов о том, что им необходимо знать, какие у них цели, границы и ограничения.

** идея 2

Больше записывать заметок и конспектов для себя.

Я и сейчас конспектирую то, что происходит.

Когда мало записываю, не всегда получается находить какие-то следы принятых решений.

Когда много записываю, получается лапша, и еще труднее находить следы принятых решений.

Пока не понимаю, могу ли я какую-то структуру для конспектов и записей использовать, чтобы в них легче ориентироваться.
